### ISSUE TITLE
Initial feedback on the xbridge documentation

### ISSUE THREAD

**Issue by jweismann** [jstevensog/wixel-sdk#8]
Hello John

I am writing mainly to express my sincere gratitude for your contributions on the
xbridge HW and SW. I recently heard about xdrip and ordered a couple of wixels etc.
to get started.

Here are my initial findings which might be useful to you in case you are to
upgrade your documentation:

1) At first I got confused wrt the source to build. I found your documentation
here https://github.com/StephenBlackWasAlreadyTaken/xDrip/wiki/xDrip-Beta

Read the awesome docs John put together here... And it took me a while before
I realized that xdrip beta (which was where I found the document) and xbridge
(your repository) was different repositories.

2) I did build with sdcc v3.3.0 (default on kubuntu 14.04) and some of the
apps in your wixel-sdk directory did not compile with this version of sdcc.
However, both xbridge2 and usb-serial build without problems so I just skipped
the ones that I didn't need. I realize that you are using an older version of
sdcc but I hope not that a specific version of the compiler is required to get
a properly build binary.

3) I forgot to solder a jumper on the charger simply because I followed your
instructions one by one. Maybe it would be a good idea to mention it in your
documentation too if others are as sloppy as me and first study the "reference"
afterwards when they find that charging is really slow.

4) I experience occasional gaps like Mathias and others have reported too but
thus far I only have a couple of days experiences so still too early to say if
this is consistent. I might try to solder an xdrip too so that we can 
cross-compare with that.

5) Not sure if I will be able to reproduce your 6 days on a 1200mAh. It dropped
from 100% to 86% in a few hours but now it seems to stabilize on 86% so maybe
I will. I will keep you updated on this. As an aside, the nightscout site
(running 0.8.1) setup for this does not show the correct battery status. It
stays on 60% and does not change at all.

Again, the main purpose of this email was really to thank you. I really
appreciate your (and all other xdrip/xbridge/nightscout developers for that
matter) efforts on this. THANKS!

Kind regards, Jacob

PS! For the reference here is a detailed listing of the parts that I used for
my first installation:

 Lithium Ion Polymer Battery - 3.7v 1200mAh from adafruit.com (PID: 258)
 Adafruit Micro Lipo w/MicroUSB Jack - USB LiIon/LiPoly charger - v1 PID: 1904
 (bought directly from adafruit, shipment to US address despite the fact that I live in Denmark, Europe)

 Wixels from www.pololu.com, bought in the US with shipment to US address.

 Note that I bought the wixels in the US but experience the same problems as others
 that bought them in Europe. Thus, I think we can exclude the location as the
 main issue.

 HM-10 BLE module from fasttech:
  https://www.fasttech.com/product/1292002-ti-cc2540-cc2541-bluetooth-4-0-ble-2540-2541

 Moto G running android 5.1

**Comment by jstevensog** [comment]
Hi Jacob,
Thanks for writing, and you are most welcome.  I am glad people are finding it of benefit.  

I updated the document with the correct links yesterday.  Apologies, I just never noticed that github changed them on me.

And yes, some of the wixel apps in the SDK don't build with this version of the SDK as some of the libraries are different from the pololu standard.  I have been slowly working on making the code independent of any library so I don't have to maintain a separate SDK.  Getting there slowly.

Point taken on the charger jumper.  I actually originally wrote the document to describe the firmware features, not as a build guide, by I will add that in the next few days.

Occasional gaps are normal (maximum a few a day, unless you go out of range), even with xDrip-wixel.  Lots of gaps are not, and appear to be due to faulty manufacture of either the chip or wixel board.  An Australian supplier we use here is aware of the problem and is replacing wixels that are reported as having it.  The replacements work fine.  In the next few months I will start work in xBridge3, and will investigate code changes and an alternative antenna to hopefully eradicate the occasional gaps.

xBridge3 will also (hopefully) have a much better battery monitoring circuit.  The current one simply monitors the battery voltage of the lipo, which is very inaccurate, and why you see the rapid drop from full charge, a plateau for a few days, and then a steady to rapid decline.  I usually recharge as soon as it hits 40%, because I know it will rapidly deplete if it hits 30%.

XBridge3 is a long way off yet.  But I intend to stick with the G4 transmitter for a year or two so the effort is worth it IMHO.

Cheers

---- jweismann wrote ----
